source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZamzamKit_Example', :exclusive => true do
  pod "ZamzamKit", :path => "../"
end

target 'ZamzamKit_Tests', :exclusive => true do
  pod "ZamzamKit", :path => "../"
end
