analyzer_rules:
- unused_import
- unused_private_declaration

excluded:
- Assets
- ZamzamKit Tests

opt_in_rules:
- array_init
- contains_over_first_not_nil
- empty_count
- empty_string
- explicit_init
- fatal_error_message
- first_where
- force_unwrapping
- function_default_parameter_at_end
- implicitly_unwrapped_optional
- last_where
- lower_acl_than_parent
- multiline_function_chains
- multiline_parameters
- multiline_parameters_brackets
- multiple_closures_with_trailing_closure
- private_action
- private_outlet
- static_operator
- switch_case_on_newline
- toggle_bool
- unneeded_break_in_switch
- unused_enumerated
- unused_optional_binding
- unused_setter_value
- vertical_parameter_alignment
- vertical_parameter_alignment_on_call
- void_return
- weak_delegate
- xctfail_message
- xct_specific_matcher
- yoda_condition

disabled_rules:
- function_body_length
- function_default_parameter_at_end
- identifier_name
- line_length
- todo
- large_tuple
- lower_acl_than_parent
- trailing_whitespace
- vertical_parameter_alignment_on_call
- multiline_function_chains
- sorted_imports

