//
//  BlogPostEntity.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import CoreData

import AlecrimCoreData

public class BlogPostEntity: NSManagedObject {

    @NSManaged public var commentsCount: Int32 // cannot mark as optional because Objective-C compatibility issues
    @NSManaged public var content: String?
    @NSManaged public var creationDate: NSDate?
    @NSManaged public var favorite: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged public var id: Int32 // cannot mark as optional because Objective-C compatibility issues
    @NSManaged public var modifiedDate: NSDate?
    @NSManaged public var publicationDate: NSDate?
    @NSManaged public var read: Bool // cannot mark as optional because Objective-C compatibility issues
    @NSManaged public var slug: String?
    @NSManaged public var status: String?
    @NSManaged public var summary: String?
    @NSManaged public var title: String?
    @NSManaged public var type: String?
    @NSManaged public var url: String?
    @NSManaged public var viewsCount: Int32 // cannot mark as optional because Objective-C compatibility issues

    @NSManaged public var author: AuthorEntity?
    @NSManaged public var image: ImageEntity?

    @NSManaged public var comments: Set<CommentEntity>
    @NSManaged public var terms: Set<TermEntity>

}

// MARK: - AlecrimCoreData query attributes

extension BlogPostEntity {

    public static let commentsCount = AlecrimCoreData.Attribute<Int32?>("commentsCount")
    public static let content = AlecrimCoreData.Attribute<String?>("content")
    public static let creationDate = AlecrimCoreData.Attribute<NSDate?>("creationDate")
    public static let favorite = AlecrimCoreData.Attribute<Bool?>("favorite")
    public static let id = AlecrimCoreData.Attribute<Int32?>("id")
    public static let modifiedDate = AlecrimCoreData.Attribute<NSDate?>("modifiedDate")
    public static let publicationDate = AlecrimCoreData.Attribute<NSDate?>("publicationDate")
    public static let read = AlecrimCoreData.Attribute<Bool?>("read")
    public static let slug = AlecrimCoreData.Attribute<String?>("slug")
    public static let status = AlecrimCoreData.Attribute<String?>("status")
    public static let summary = AlecrimCoreData.Attribute<String?>("summary")
    public static let title = AlecrimCoreData.Attribute<String?>("title")
    public static let type = AlecrimCoreData.Attribute<String?>("type")
    public static let url = AlecrimCoreData.Attribute<String?>("url")
    public static let viewsCount = AlecrimCoreData.Attribute<Int32?>("viewsCount")

    public static let author = AuthorEntityAttribute<AuthorEntity?>("author")
    public static let image = ImageEntityAttribute<ImageEntity?>("image")

    public static let comments = AlecrimCoreData.EntitySetAttribute<Set<CommentEntity>>("comments")
    public static let terms = AlecrimCoreData.EntitySetAttribute<Set<TermEntity>>("terms")

}

public class BlogPostEntityAttribute<T>: AlecrimCoreData.SingleEntityAttribute<T> {

    public override init(_ name: String) { super.init(name) }

    public lazy var commentsCount: AlecrimCoreData.Attribute<Int32?> = { AlecrimCoreData.Attribute<Int32?>("\(self.___name).commentsCount") }()
    public lazy var content: AlecrimCoreData.Attribute<String?> = { AlecrimCoreData.Attribute<String?>("\(self.___name).content") }()
    public lazy var creationDate: AlecrimCoreData.Attribute<NSDate?> = { AlecrimCoreData.Attribute<NSDate?>("\(self.___name).creationDate") }()
    public lazy var favorite: AlecrimCoreData.Attribute<Bool?> = { AlecrimCoreData.Attribute<Bool?>("\(self.___name).favorite") }()
    public lazy var id: AlecrimCoreData.Attribute<Int32?> = { AlecrimCoreData.Attribute<Int32?>("\(self.___name).id") }()
    public lazy var modifiedDate: AlecrimCoreData.Attribute<NSDate?> = { AlecrimCoreData.Attribute<NSDate?>("\(self.___name).modifiedDate") }()
    public lazy var publicationDate: AlecrimCoreData.Attribute<NSDate?> = { AlecrimCoreData.Attribute<NSDate?>("\(self.___name).publicationDate") }()
    public lazy var read: AlecrimCoreData.Attribute<Bool?> = { AlecrimCoreData.Attribute<Bool?>("\(self.___name).read") }()
    public lazy var slug: AlecrimCoreData.Attribute<String?> = { AlecrimCoreData.Attribute<String?>("\(self.___name).slug") }()
    public lazy var status: AlecrimCoreData.Attribute<String?> = { AlecrimCoreData.Attribute<String?>("\(self.___name).status") }()
    public lazy var summary: AlecrimCoreData.Attribute<String?> = { AlecrimCoreData.Attribute<String?>("\(self.___name).summary") }()
    public lazy var title: AlecrimCoreData.Attribute<String?> = { AlecrimCoreData.Attribute<String?>("\(self.___name).title") }()
    public lazy var type: AlecrimCoreData.Attribute<String?> = { AlecrimCoreData.Attribute<String?>("\(self.___name).type") }()
    public lazy var url: AlecrimCoreData.Attribute<String?> = { AlecrimCoreData.Attribute<String?>("\(self.___name).url") }()
    public lazy var viewsCount: AlecrimCoreData.Attribute<Int32?> = { AlecrimCoreData.Attribute<Int32?>("\(self.___name).viewsCount") }()

    public lazy var author: AuthorEntityAttribute<AuthorEntity?> = { AuthorEntityAttribute<AuthorEntity?>("\(self.___name).author") }()
    public lazy var image: ImageEntityAttribute<ImageEntity?> = { ImageEntityAttribute<ImageEntity?>("\(self.___name).image") }()

    public lazy var comments: AlecrimCoreData.EntitySetAttribute<Set<CommentEntity>> = { AlecrimCoreData.EntitySetAttribute<Set<CommentEntity>>("\(self.___name).comments") }()
    public lazy var terms: AlecrimCoreData.EntitySetAttribute<Set<TermEntity>> = { AlecrimCoreData.EntitySetAttribute<Set<TermEntity>>("\(self.___name).terms") }()

}
