//
//  DataContext.swift
//
//  This code was generated by AlecrimCoreData code generator tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//

import Foundation
import AlecrimCoreData

public class DataContext: AlecrimCoreData.Context {

    public var authors: AlecrimCoreData.Table<AuthorEntity> { return AlecrimCoreData.Table<AuthorEntity>(context: self) }
    public var blogPosts: AlecrimCoreData.Table<BlogPostEntity> { return AlecrimCoreData.Table<BlogPostEntity>(context: self) }
    public var comments: AlecrimCoreData.Table<CommentEntity> { return AlecrimCoreData.Table<CommentEntity>(context: self) }
    public var images: AlecrimCoreData.Table<ImageEntity> { return AlecrimCoreData.Table<ImageEntity>(context: self) }
    public var notifications: AlecrimCoreData.Table<NotificationEntity> { return AlecrimCoreData.Table<NotificationEntity>(context: self) }
    public var terms: AlecrimCoreData.Table<TermEntity> { return AlecrimCoreData.Table<TermEntity>(context: self) }

}
